2021-04-14 21:39:06,794 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 6076f07ad16412217098032a mem_id=2563538292112
2021-04-14 21:39:06,798 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  6076f07ad16412217098032a 
2021-04-14 21:39:06,807 - DEBUG - ServiceNode - [EtcdSupport.py:541]: we have create ServiceFinder
2021-04-14 21:39:06,812 - DEBUG - ServiceFinder - [EtcdSupport.py:344]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 21:39:06,819 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 21:39:06,823 - DEBUG - ServiceFinder - [EtcdSupport.py:315]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-04-14 21:39:06,824 - DEBUG - ServiceFinder - [EtcdSupport.py:269]: init service info from etcd success, will going to watch, at etcd index -> 3510
2021-04-14 21:39:06,831 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 21:39:06,833 - DEBUG - ServiceRegister - [EtcdSupport.py:160]: regist service : battle_server success, {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T13:42:06.8215893Z","ttl":180,"modifiedIndex":3511,"createdIndex":3511}}

2021-04-14 21:39:06,845 - DEBUG - ServiceFinder - [EtcdSupport.py:430]: recv watch set service node info--> battle_server: ('127.0.0.1', 8888) - [3511]
2021-04-14 21:57:00,973 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 6076f4acd164121bd05c1745 mem_id=1426968086464
2021-04-14 21:57:00,974 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  6076f4acd164121bd05c1745 
2021-04-14 21:57:00,981 - DEBUG - ServiceNode - [EtcdSupport.py:542]: we have create ServiceFinder
2021-04-14 21:57:00,986 - DEBUG - ServiceFinder - [EtcdSupport.py:344]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 21:57:00,991 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 21:57:00,994 - DEBUG - ServiceFinder - [EtcdSupport.py:315]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-04-14 21:57:00,997 - DEBUG - ServiceFinder - [EtcdSupport.py:269]: init service info from etcd success, will going to watch, at etcd index -> 3515
2021-04-14 21:57:01,003 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 21:57:01,005 - DEBUG - ServiceRegister - [EtcdSupport.py:160]: regist service : battle_server success, {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:00:00.9930076Z","ttl":180,"modifiedIndex":3516,"createdIndex":3516}}

2021-04-14 21:57:01,026 - DEBUG - ServiceFinder - [EtcdSupport.py:431]: recv watch set service node info--> battle_server: ('127.0.0.1', 8888) - [3516]
2021-04-14 22:34:04,150 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 6076fd5cd1641222d0bf5e4d mem_id=2148460595232
2021-04-14 22:34:04,152 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  6076fd5cd1641222d0bf5e4d 
2021-04-14 22:34:04,165 - DEBUG - ServiceNode - [EtcdSupport.py:526]: we have create ServiceFinder
2021-04-14 22:34:04,175 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,181 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,186 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,188 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,189 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,191 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,192 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:04,197 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,198 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,199 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,202 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 22:34:04,204 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,205 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,206 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,208 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:04,210 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,213 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,215 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,216 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,218 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,219 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,220 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,222 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,224 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,227 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,229 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,230 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,232 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,234 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,235 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,237 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,239 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,241 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,243 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,244 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,246 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,247 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,249 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:04,251 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,253 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:04,256 - ERROR - ServiceRegister - [EtcdSupport.py:172]: regist service : battle_server error
2021-04-14 22:34:04,257 - CRITICAL - ServiceRegister - [EtcdSupport.py:173]: on_traceback, type:<class 'TypeError'>, value:cannot unpack non-iterable coroutine object, traceback:<class 'TypeError'>
cannot unpack non-iterable coroutine object
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 158, in _do_regist
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001F43A3DB400>, 'service_name': 'battle_server', 'data': 'ttl=180', 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888'}
2021-04-14 22:34:04,258 - ERROR - ServiceRegister - [EtcdSupport.py:184]: regist service battle_server fail
2021-04-14 22:34:04,260 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:04,262 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,267 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,268 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 22:34:04,272 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys?recursive=true'}
2021-04-14 22:34:04,274 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:04,278 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:04,281 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 22:34:04,285 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys?recursive=true'}
2021-04-14 22:34:04,287 - CRITICAL - TcpServer - [TcpServer.py:234]: on_traceback, type:<class 'Exception'>, value:init service info from etcd fail, traceback:<class 'Exception'>
init service info from etcd fail
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 231, in _main
    locals={'self': <TcpServer.TcpServer object at 0x000001F438E6D3D0>, '_etcd_support_task': <Task finished name='Task-2' coro=<TcpServer._start_etcd_task() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py:236> exception=Exception('init service info from etcd fail') created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>, '_start_srv_task': <Task pending name='Task-3' coro=<TcpServer._start_server_task() running at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py:192> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001F43A481190>()] created at C:\Program Files\Python38\lib\asyncio\base_events.py:422> created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 252, in _start_etcd_task
    locals={'self': <TcpServer.TcpServer object at 0x000001F438E6D3D0>, 'etcd_addr_list': [('127.0.0.1', '2379'), ('127.0.0.1', '2381'), ('127.0.0.1', '2383')], 'my_addr': ('127.0.0.1', '8888')}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 539, in start
    locals={'self': <core.EtcdSupport.ServiceNode object at 0x000001F43A3DBC70>, 'session': <aiohttp.client.ClientSession object at 0x000001F43A3DBCD0>, 'register_task': <Task finished name='Task-4' coro=<ServiceRegister.start() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py:100> result=None created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>, 'finder_task': <Task finished name='Task-5' coro=<ServiceFinder.start() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py:268> exception=Exception('init service info from etcd fail') created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 279, in start
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001F43A3DBD60>, 'session': <aiohttp.client.ClientSession object at 0x000001F43A3DBCD0>}
2021-04-14 22:34:04,290 - CRITICAL - TcpServer - [TcpServer.py:203]: on_traceback, type:<class 'asyncio.exceptions.CancelledError'>, value:, traceback:<class 'asyncio.exceptions.CancelledError'>

  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 192, in _start_server_task
    locals={'self': <TcpServer.TcpServer object at 0x000001F438E6D3D0>, 'server': <Server sockets=()>, 'addr': ('127.0.0.1', 8888)}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 366, in serve_forever
    locals={'self': <Server sockets=()>, }
2021-04-14 22:34:30,227 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 6076fd76d164120f94572a8a mem_id=1885710387136
2021-04-14 22:34:30,229 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  6076fd76d164120f94572a8a 
2021-04-14 22:34:30,236 - DEBUG - ServiceNode - [EtcdSupport.py:526]: we have create ServiceFinder
2021-04-14 22:34:30,240 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:30,245 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:34:30,250 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:30,251 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:30,257 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 22:34:30,259 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:30,261 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:30,266 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:30,268 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:30,277 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:30,278 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:34:30,284 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys?recursive=true'}
2021-04-14 22:34:30,286 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:30,292 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : battle_server success, {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:37:30.2746518Z","ttl":180,"modifiedIndex":3519,"createdIndex":3519}}

2021-04-14 22:34:30,294 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:30,295 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:30,299 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:30,301 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 22:34:30,305 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys?recursive=true'}
2021-04-14 22:34:30,307 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2381/v2/keys?recursive=true
2021-04-14 22:34:30,312 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys?recursive=true'}
2021-04-14 22:34:30,313 - DEBUG - ServiceFinder - [EtcdSupport.py:347]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-04-14 22:34:30,317 - CRITICAL - ServiceFinder - [EtcdSupport.py:364]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 349, in _init_info
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys?recursive=true'}
2021-04-14 22:34:36,232 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:34:42,234 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:34:48,224 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:34:54,229 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:00,233 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:06,222 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:12,226 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:18,233 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:24,223 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:30,226 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:36,231 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:42,236 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:48,298 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:35:54,304 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:36:00,303 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:36:06,306 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:36:12,294 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.2925172, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,299 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.2945108, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,310 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.309459, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,313 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:36:12,315 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A430>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'service_name': 'battle_server', 'ttl_refresh_data': 'ttl=180&refresh=True'}
2021-04-14 22:36:12,316 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.3154404, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,318 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.3164368, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,324 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.323413, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,327 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,328 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.327397, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,330 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.3284183, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,339 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.3383632, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,342 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D1CF9D0>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,343 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.3413725, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,345 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.344342, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,352 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.3513186, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,355 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,356 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.3553114, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,357 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.3562999, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,366 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.3652716, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,369 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D1CF9D0>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,370 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.3692555, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,372 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.3702545, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,389 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.387196, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,391 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,392 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.3912685, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,394 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.3922665, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,412 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.411115, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,416 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D1CF9D0>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,417 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.4151258, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,420 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.417095, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,438 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.4360929, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,441 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,443 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.4410124, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,444 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.443095, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,464 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.4629407, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,467 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D1CF9D0>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,469 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618410972.4679654, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,470 - DEBUG - ServiceRegister - [EtcdSupport.py:199]: inside before, time.time()=1618410972.469952, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,488 - DEBUG - ServiceRegister - [EtcdSupport.py:201]: inside after, time.time()=1618410972.4878561, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:36:12,491 - CRITICAL - ServiceRegister - [EtcdSupport.py:219]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 209, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', 'service_name': 'battle_server'}
2021-04-14 22:36:12,492 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,506 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [200]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 0, 'service_name': 'battle_server'}
2021-04-14 22:36:12,508 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,519 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 1, 'service_name': 'battle_server'}
2021-04-14 22:36:12,520 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,529 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 2, 'service_name': 'battle_server'}
2021-04-14 22:36:12,532 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,540 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 3, 'service_name': 'battle_server'}
2021-04-14 22:36:12,542 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,552 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 4, 'service_name': 'battle_server'}
2021-04-14 22:36:12,553 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,563 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 5, 'service_name': 'battle_server'}
2021-04-14 22:36:12,565 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,574 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 6, 'service_name': 'battle_server'}
2021-04-14 22:36:12,576 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,584 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 7, 'service_name': 'battle_server'}
2021-04-14 22:36:12,585 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,595 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 8, 'service_name': 'battle_server'}
2021-04-14 22:36:12,596 - DEBUG - ServiceRegister - [EtcdSupport.py:226]: try delete service: battle_server
2021-04-14 22:36:12,604 - CRITICAL - ServiceRegister - [EtcdSupport.py:237]: on_traceback, type:<class 'NameError'>, value:name 'r_text' is not defined, traceback:<class 'NameError'>
name 'r_text' is not defined
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 229, in _process_regist_and_ttl
    locals={'self': <core.EtcdSupport.ServiceRegister object at 0x000001B70D1BB3A0>, 'request_etcd_put': <function ServiceRegister._process_regist_and_ttl.<locals>.request_etcd_put at 0x000001B70D35A550>, 'r': <Response [404]>, 'now_url': 'http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888', 'ttl_refresh_data': 'ttl=180&refresh=True', '_': 9, 'service_name': 'battle_server'}
2021-04-14 22:36:12,606 - CRITICAL - TcpServer - [TcpServer.py:234]: on_traceback, type:<class 'Exception'>, value:init service info from etcd fail, traceback:<class 'Exception'>
init service info from etcd fail
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 231, in _main
    locals={'self': <TcpServer.TcpServer object at 0x000001B70BC2D3D0>, '_etcd_support_task': <Task finished name='Task-2' coro=<TcpServer._start_etcd_task() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py:236> exception=Exception('init service info from etcd fail') created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>, '_start_srv_task': <Task pending name='Task-3' coro=<TcpServer._start_server_task() running at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py:192> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001B70D2611C0>()] created at C:\Program Files\Python38\lib\asyncio\base_events.py:422> created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 252, in _start_etcd_task
    locals={'self': <TcpServer.TcpServer object at 0x000001B70BC2D3D0>, 'etcd_addr_list': [('127.0.0.1', '2379'), ('127.0.0.1', '2381'), ('127.0.0.1', '2383')], 'my_addr': ('127.0.0.1', '8888')}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 539, in start
    locals={'self': <core.EtcdSupport.ServiceNode object at 0x000001B70D1BBC10>, 'session': <aiohttp.client.ClientSession object at 0x000001B70D1BBC70>, 'register_task': <Task finished name='Task-4' coro=<ServiceRegister.start() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py:100> result=None created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>, 'finder_task': <Task finished name='Task-5' coro=<ServiceFinder.start() done, defined at C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py:268> exception=Exception('init service info from etcd fail') created at C:\Program Files\Python38\lib\asyncio\tasks.py:382>}
  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\core\EtcdSupport.py", line 279, in start
    locals={'self': <core.EtcdSupport.ServiceFinder object at 0x000001B70D1BBD00>, 'session': <aiohttp.client.ClientSession object at 0x000001B70D1BBC70>}
2021-04-14 22:36:12,609 - CRITICAL - TcpServer - [TcpServer.py:203]: on_traceback, type:<class 'asyncio.exceptions.CancelledError'>, value:, traceback:<class 'asyncio.exceptions.CancelledError'>

  File "C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpServer.py", line 192, in _start_server_task
    locals={'self': <TcpServer.TcpServer object at 0x000001B70BC2D3D0>, 'server': <Server sockets=()>, 'addr': ('127.0.0.1', 8888)}
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 366, in serve_forever
    locals={'self': <Server sockets=()>, }
2021-04-14 22:46:26,581 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 60770042d16412454cc128f5 mem_id=1179424574528
2021-04-14 22:46:26,583 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60770042d16412454cc128f5 
2021-04-14 22:46:26,590 - DEBUG - ServiceNode - [EtcdSupport.py:531]: we have create ServiceFinder
2021-04-14 22:46:26,595 - DEBUG - ServiceFinder - [EtcdSupport.py:351]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:46:26,599 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:46:26,605 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 22:46:26,617 - DEBUG - ServiceFinder - [EtcdSupport.py:276]: init service info from etcd success, will going to watch, at etcd index -> 3530
2021-04-14 22:46:26,624 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : battle_server success, {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:49:26.613379Z","ttl":180,"modifiedIndex":3531,"createdIndex":3531}}

2021-04-14 22:46:26,638 - DEBUG - ServiceFinder - [EtcdSupport.py:420]: recv watch set service node info--> battle_server: ('127.0.0.1', 8888) - [3531]
2021-04-14 22:46:32,584 - ERROR - ServerEntity.LoadReporter - [LoadReporter.py:41]: can not find dispatcher_service_addr
2021-04-14 22:46:34,484 - DEBUG - ServiceFinder - [EtcdSupport.py:420]: recv watch set service node info--> dispatcher_service: ('127.0.0.1', 9100) - [3532]
2021-04-14 22:47:43,478 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3532 -> 3532
2021-04-14 22:48:10,629 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618411690.6273134, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:48:10,646 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618411690.645244, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:51:10.6362815Z","ttl":180,"modifiedIndex":3533,"createdIndex":3533},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:49:26.613379Z","ttl":76,"modifiedIndex":3531,"createdIndex":3531}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:48:46,478 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3532 -> 3532
2021-04-14 22:49:47,487 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3532 -> 3534
2021-04-14 22:49:55,647 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618411795.6467323, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:49:55,661 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618411795.6606858, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:52:55.6547083Z","ttl":180,"modifiedIndex":3535,"createdIndex":3535},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:51:10.6362815Z","ttl":75,"modifiedIndex":3533,"createdIndex":3533}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:50:53,497 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3534 -> 3534
2021-04-14 22:51:44,664 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618411904.662957, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:51:44,680 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618411904.679928, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:54:44.672038Z","ttl":180,"modifiedIndex":3537,"createdIndex":3537},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:52:55.6547083Z","ttl":71,"modifiedIndex":3535,"createdIndex":3535}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:51:53,492 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3534 -> 3536
2021-04-14 22:52:54,497 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3536 -> 3538
2021-04-14 22:53:29,682 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412009.6803198, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:53:29,699 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412009.6973777, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:56:29.689377Z","ttl":180,"modifiedIndex":3539,"createdIndex":3539},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:54:44.672038Z","ttl":75,"modifiedIndex":3537,"createdIndex":3537}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:54:04,511 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3538 -> 3538
2021-04-14 22:55:09,712 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412109.7117763, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:55:09,727 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412109.726621, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:58:09.7196452Z","ttl":180,"modifiedIndex":3541,"createdIndex":3541},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:56:29.689377Z","ttl":80,"modifiedIndex":3539,"createdIndex":3539}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:55:10,514 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3538 -> 3540
2021-04-14 22:56:18,514 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3540 -> 3541
2021-04-14 22:56:52,740 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412212.7384667, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:56:52,754 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412212.7534058, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:59:52.7483959Z","ttl":180,"modifiedIndex":3543,"createdIndex":3543},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:58:09.7196452Z","ttl":77,"modifiedIndex":3541,"createdIndex":3541}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:57:20,511 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3541 -> 3542
2021-04-14 22:58:24,519 - DEBUG - ServiceFinder - [EtcdSupport.py:473]: etcd watch timeout, rest watch index 3542 -> 3544
2021-04-14 22:58:24,726 - WARNING - TcpConn - [TcpConn.py:173]: connection is closed by error: [WinError 64] The specified network name is no longer available
2021-04-14 22:58:25,976 - DEBUG - ServiceFinder - [EtcdSupport.py:420]: recv watch set service node info--> dispatcher_service: ('127.0.0.1', 9100) - [3545]
2021-04-14 22:58:25,978 - DEBUG - ServiceFinder - [EtcdSupport.py:298]: duplicate service info  -> dispatcher_service:('127.0.0.1', 9100)
2021-04-14 22:58:33,482 - DEBUG - ServerEntity.LoadReporter - [ServerEntity.py:25]: __init__ create entity LoadReporter with id 60770319d1641247d8358bb0 mem_id=2214901427312
2021-04-14 22:58:33,484 - DEBUG - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60770319d1641247d8358bb0 
2021-04-14 22:58:33,495 - DEBUG - ServiceNode - [EtcdSupport.py:533]: we have create ServiceFinder
2021-04-14 22:58:33,505 - DEBUG - ServiceFinder - [EtcdSupport.py:352]: _init_info, now_url: http://127.0.0.1:2383/v2/keys?recursive=true
2021-04-14 22:58:33,510 - DEBUG - ServiceRegister - [EtcdSupport.py:155]: _do_regist: now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 22:58:33,520 - DEBUG - TcpServer - [TcpServer.py:189]: Server on ('127.0.0.1', 8888)
2021-04-14 22:58:33,544 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-04-14 22:58:33,555 - DEBUG - ServiceFinder - [EtcdSupport.py:323]: add service node info--> battle_server: ('127.0.0.1', 8888)
2021-04-14 22:58:33,556 - DEBUG - ServiceFinder - [EtcdSupport.py:277]: init service info from etcd success, will going to watch, at etcd index -> 3545
2021-04-14 22:58:33,565 - DEBUG - ServiceRegister - [EtcdSupport.py:163]: regist service : battle_server success, {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:01:33.535113Z","ttl":180,"modifiedIndex":3546,"createdIndex":3546},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T14:59:52.7483959Z","ttl":80,"modifiedIndex":3543,"createdIndex":3543}}

2021-04-14 22:58:33,576 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> battle_server: ('127.0.0.1', 8888) - [3546]
2021-04-14 22:58:33,578 - DEBUG - ServiceFinder - [EtcdSupport.py:299]: duplicate service info  -> battle_server:('127.0.0.1', 8888)
2021-04-14 22:58:35,624 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> battle_server: ('127.0.0.1', 9003) - [3547]
2021-04-14 22:58:37,816 - DEBUG - ServiceFinder - [EtcdSupport.py:422]: recv watch set service node info--> battle_server: ('127.0.0.1', 9001) - [3548]
2021-04-14 22:59:39,830 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3548 -> 3548
2021-04-14 23:00:19,580 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412419.5783699, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:00:19,595 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412419.5942457, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:03:19.5872692Z","ttl":180,"modifiedIndex":3550,"createdIndex":3550},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:01:33.535113Z","ttl":74,"modifiedIndex":3546,"createdIndex":3546}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:00:47,833 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3548 -> 3548
2021-04-14 23:01:54,833 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3548 -> 3552
2021-04-14 23:02:03,592 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412523.5905635, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:02:03,608 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412523.6075068, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:05:03.599524Z","ttl":180,"modifiedIndex":3554,"createdIndex":3554},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:03:19.5872692Z","ttl":76,"modifiedIndex":3550,"createdIndex":3550}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:03:03,829 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3552 -> 3553
2021-04-14 23:03:48,605 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412628.6041794, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:03:48,621 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412628.6191423, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:06:48.6111683Z","ttl":180,"modifiedIndex":3558,"createdIndex":3558},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:05:03.599524Z","ttl":75,"modifiedIndex":3554,"createdIndex":3554}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:04:12,833 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3553 -> 3556
2021-04-14 23:05:19,839 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3556 -> 3560
2021-04-14 23:05:36,622 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412736.6204884, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:05:36,637 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412736.63546, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:08:36.6304023Z","ttl":180,"modifiedIndex":3562,"createdIndex":3562},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:06:48.6111683Z","ttl":72,"modifiedIndex":3558,"createdIndex":3558}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:06:26,848 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3560 -> 3561
2021-04-14 23:07:18,633 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412838.632471, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:07:18,650 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412838.6485403, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:10:18.639535Z","ttl":180,"modifiedIndex":3566,"createdIndex":3566},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:08:36.6304023Z","ttl":78,"modifiedIndex":3562,"createdIndex":3562}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:07:36,849 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3561 -> 3564
2021-04-14 23:08:42,859 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3564 -> 3567
2021-04-14 23:09:08,660 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618412948.6589508, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:09:08,676 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618412948.6758347, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:12:08.6677734Z","ttl":180,"modifiedIndex":3570,"createdIndex":3570},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:10:18.639535Z","ttl":70,"modifiedIndex":3566,"createdIndex":3566}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:09:52,861 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3567 -> 3568
2021-04-14 23:10:58,686 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413058.6841788, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:10:58,701 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413058.700113, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:13:58.6911538Z","ttl":180,"modifiedIndex":3574,"createdIndex":3574},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:12:08.6677734Z","ttl":70,"modifiedIndex":3570,"createdIndex":3570}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:10:58,875 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3568 -> 3572
2021-04-14 23:12:07,891 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3572 -> 3574
2021-04-14 23:12:46,692 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413166.6903613, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:12:46,706 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413166.7052603, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:15:46.6981858Z","ttl":180,"modifiedIndex":3578,"createdIndex":3578},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:13:58.6911538Z","ttl":72,"modifiedIndex":3574,"createdIndex":3574}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:13:16,904 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3574 -> 3576
2021-04-14 23:14:20,919 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3576 -> 3580
2021-04-14 23:14:29,704 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413269.702048, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:14:29,716 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413269.715085, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:17:29.7090173Z","ttl":180,"modifiedIndex":3582,"createdIndex":3582},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:15:46.6981858Z","ttl":77,"modifiedIndex":3578,"createdIndex":3578}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:15:30,933 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3580 -> 3581
2021-04-14 23:16:17,722 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413377.7206762, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:16:17,737 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413377.7356017, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:19:17.7286261Z","ttl":180,"modifiedIndex":3588,"createdIndex":3588},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:17:29.7090173Z","ttl":72,"modifiedIndex":3582,"createdIndex":3582}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:16:32,945 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3581 -> 3584
2021-04-14 23:17:38,936 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3584 -> 3588
2021-04-14 23:18:03,741 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413483.739742, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:18:03,754 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413483.7535853, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:21:03.7475746Z","ttl":180,"modifiedIndex":3592,"createdIndex":3592},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:19:17.7286261Z","ttl":74,"modifiedIndex":3588,"createdIndex":3588}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:18:47,943 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3588 -> 3588
2021-04-14 23:19:53,756 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413593.7542553, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:19:53,770 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413593.768209, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:22:53.7622278Z","ttl":180,"modifiedIndex":3596,"createdIndex":3596},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:21:03.7475746Z","ttl":70,"modifiedIndex":3592,"createdIndex":3592}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:19:57,941 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3588 -> 3592
2021-04-14 23:21:04,938 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3592 -> 3596
2021-04-14 23:21:41,768 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413701.767781, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:21:41,783 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413701.7821112, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:24:41.7751745Z","ttl":180,"modifiedIndex":3600,"createdIndex":3600},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:22:53.7622278Z","ttl":72,"modifiedIndex":3596,"createdIndex":3596}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:22:11,935 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3596 -> 3596
2021-04-14 23:23:21,938 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3596 -> 3600
2021-04-14 23:23:25,783 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413805.7818868, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:23:25,796 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413805.7957559, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:26:25.7917755Z","ttl":180,"modifiedIndex":3604,"createdIndex":3604},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:24:41.7751745Z","ttl":76,"modifiedIndex":3600,"createdIndex":3600}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:24:26,954 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3600 -> 3603
2021-04-14 23:25:05,791 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618413905.7897546, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:25:05,802 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618413905.8016891, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:28:05.7966985Z","ttl":180,"modifiedIndex":3608,"createdIndex":3608},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:26:25.7917755Z","ttl":80,"modifiedIndex":3604,"createdIndex":3604}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:25:36,965 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3603 -> 3604
2021-04-14 23:26:42,965 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3604 -> 3608
2021-04-14 23:26:51,806 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414011.8043513, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:26:51,820 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414011.8172321, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:29:51.8122981Z","ttl":180,"modifiedIndex":3612,"createdIndex":3612},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:28:05.7966985Z","ttl":74,"modifiedIndex":3608,"createdIndex":3608}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:27:49,961 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3608 -> 3609
2021-04-14 23:28:38,816 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414118.8142412, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:28:38,829 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414118.8280768, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:31:38.8221817Z","ttl":180,"modifiedIndex":3616,"createdIndex":3616},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:29:51.8122981Z","ttl":73,"modifiedIndex":3612,"createdIndex":3612}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:28:51,957 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3609 -> 3612
2021-04-14 23:29:56,962 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3612 -> 3616
2021-04-14 23:30:19,831 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414219.8306768, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:30:19,845 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414219.8445182, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:33:19.8375412Z","ttl":180,"modifiedIndex":3619,"createdIndex":3619},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:31:38.8221817Z","ttl":79,"modifiedIndex":3616,"createdIndex":3616}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:31:04,973 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3616 -> 3616
2021-04-14 23:32:06,972 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3616 -> 3620
2021-04-14 23:32:08,847 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414328.846612, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:32:08,860 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414328.858571, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:35:08.8535888Z","ttl":180,"modifiedIndex":3623,"createdIndex":3623},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:33:19.8375412Z","ttl":71,"modifiedIndex":3619,"createdIndex":3619}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:33:09,970 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3620 -> 3622
2021-04-14 23:33:51,858 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414431.857927, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:33:51,872 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414431.8708866, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:36:51.864934Z","ttl":180,"modifiedIndex":3627,"createdIndex":3627},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:35:08.8535888Z","ttl":77,"modifiedIndex":3623,"createdIndex":3623}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:34:18,964 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3622 -> 3624
2021-04-14 23:35:27,971 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3624 -> 3628
2021-04-14 23:35:36,878 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414536.8772233, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:35:36,887 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414536.886048, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:38:36.8811819Z","ttl":180,"modifiedIndex":3631,"createdIndex":3631},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:36:51.864934Z","ttl":75,"modifiedIndex":3627,"createdIndex":3627}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:36:27,987 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3628 -> 3629
2021-04-14 23:37:24,882 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414644.8809178, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:37:24,894 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414644.8933427, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:40:24.8878943Z","ttl":180,"modifiedIndex":3635,"createdIndex":3635},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:38:36.8811819Z","ttl":72,"modifiedIndex":3631,"createdIndex":3631}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:37:34,003 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3629 -> 3632
2021-04-14 23:38:35,010 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3632 -> 3636
2021-04-14 23:39:06,892 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414746.8910885, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:39:06,904 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414746.9030583, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:42:06.8970783Z","ttl":180,"modifiedIndex":3639,"createdIndex":3639},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:40:24.8878943Z","ttl":78,"modifiedIndex":3635,"createdIndex":3635}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:39:42,008 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3636 -> 3636
2021-04-14 23:40:51,018 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3636 -> 3640
2021-04-14 23:40:52,917 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414852.9160345, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:40:52,929 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414852.9289274, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:43:52.9238969Z","ttl":180,"modifiedIndex":3643,"createdIndex":3643},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:42:06.8970783Z","ttl":74,"modifiedIndex":3639,"createdIndex":3639}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:41:59,019 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3640 -> 3642
2021-04-14 23:42:37,935 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618414957.9335227, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:42:37,950 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618414957.9484637, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:45:37.9404859Z","ttl":180,"modifiedIndex":3647,"createdIndex":3647},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:43:52.9238969Z","ttl":75,"modifiedIndex":3643,"createdIndex":3643}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:42:59,028 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3642 -> 3644
2021-04-14 23:44:07,035 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3644 -> 3648
2021-04-14 23:44:27,966 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415067.9645734, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:44:27,981 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415067.9796343, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:47:27.9735638Z","ttl":180,"modifiedIndex":3651,"createdIndex":3651},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:45:37.9404859Z","ttl":70,"modifiedIndex":3647,"createdIndex":3647}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:45:14,033 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3648 -> 3649
2021-04-14 23:46:08,983 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415168.9816582, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:46:08,997 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415168.9966989, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:49:08.9887136Z","ttl":180,"modifiedIndex":3655,"createdIndex":3655},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:47:27.9735638Z","ttl":79,"modifiedIndex":3651,"createdIndex":3651}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:46:15,045 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3649 -> 3652
2021-04-14 23:47:19,052 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3652 -> 3655
2021-04-14 23:47:57,000 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415276.9995625, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:47:57,013 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415277.012574, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:50:57.0066465Z","ttl":180,"modifiedIndex":3659,"createdIndex":3659},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:49:08.9887136Z","ttl":72,"modifiedIndex":3655,"createdIndex":3655}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:48:27,052 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3655 -> 3656
2021-04-14 23:49:35,043 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3656 -> 3660
2021-04-14 23:49:47,026 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415387.0256138, refresh service battle_server, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:49:47,037 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415387.036576, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:52:47.0307002Z","ttl":180,"modifiedIndex":3664,"createdIndex":3664},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:50:57.0066465Z","ttl":70,"modifiedIndex":3659,"createdIndex":3659}}
, now_url: http://127.0.0.1:2381/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:50:43,043 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3660 -> 3662
2021-04-14 23:51:28,041 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415488.0408854, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:51:28,058 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415488.056728, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:54:28.0487536Z","ttl":180,"modifiedIndex":3667,"createdIndex":3667},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:52:47.0307002Z","ttl":79,"modifiedIndex":3664,"createdIndex":3664}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:51:48,050 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3662 -> 3664
2021-04-14 23:52:58,055 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3664 -> 3668
2021-04-14 23:53:12,063 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415592.0621998, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:53:12,077 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415592.0760493, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:56:12.0690743Z","ttl":180,"modifiedIndex":3671,"createdIndex":3671},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:54:28.0487536Z","ttl":76,"modifiedIndex":3667,"createdIndex":3667}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:53:58,073 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3668 -> 3668
2021-04-14 23:54:53,085 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415693.0844767, refresh service battle_server, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:54:53,096 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415693.0954413, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:57:53.0904798Z","ttl":180,"modifiedIndex":3675,"createdIndex":3675},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:56:12.0690743Z","ttl":79,"modifiedIndex":3671,"createdIndex":3671}}
, now_url: http://127.0.0.1:2383/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:55:05,076 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3668 -> 3672
2021-04-14 23:56:12,085 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3672 -> 3675
2021-04-14 23:56:40,100 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415800.0974576, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:56:40,115 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415800.114354, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:59:40.1064213Z","ttl":180,"modifiedIndex":3679,"createdIndex":3679},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:57:53.0904798Z","ttl":73,"modifiedIndex":3675,"createdIndex":3675}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:57:15,101 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3675 -> 3676
2021-04-14 23:58:22,118 - DEBUG - ServiceRegister - [EtcdSupport.py:196]: outside, time.time()=1618415902.1166139, refresh service battle_server, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:58:22,135 - DEBUG - ServiceRegister - [EtcdSupport.py:214]: time.time()=1618415902.1345544, refresh service success: battle_server: {"action":"set","node":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T16:01:22.1256743Z","ttl":180,"modifiedIndex":3682,"createdIndex":3682},"prevNode":{"key":"/services/battle_server/127.0.0.1|8888","value":"","expiration":"2021-04-14T15:59:40.1064213Z","ttl":78,"modifiedIndex":3679,"createdIndex":3679}}
, now_url: http://127.0.0.1:2379/v2/keys/services/battle_server/127.0.0.1|8888
2021-04-14 23:58:23,117 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3676 -> 3680
2021-04-14 23:59:26,129 - DEBUG - ServiceFinder - [EtcdSupport.py:475]: etcd watch timeout, rest watch index 3680 -> 3682
