2021-07-05 00:25:26,285 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1e0f645f5b67d16ca9710 mem_id=1862405137408
2021-07-05 00:25:26,286 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1e0f645f5b67d16ca9710 
2021-07-05 00:25:26,303 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 00:25:26,304 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 00:25:26,335 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9100)
2021-07-05 00:25:30,549 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1e0fabd2ddafad6fc35ed mem_id=1789543973984
2021-07-05 00:25:30,551 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1e0fabd2ddafad6fc35ed 
2021-07-05 00:25:30,560 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 00:25:30,561 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 00:25:30,583 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9100)
2021-07-05 00:25:33,575 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 00:25:33,580 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-05 00:25:33,581 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 00:25:33,582 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 5951
2021-07-05 00:25:40,621 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 14402) is connected !!!!
2021-07-05 00:25:40,626 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14402)
2021-07-05 00:25:46,505 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 14409) is connected !!!!
2021-07-05 00:25:46,511 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14409)
2021-07-05 00:28:18,980 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1e1a265fc8e9c85c494c1 mem_id=2766430733408
2021-07-05 00:28:18,981 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1e1a265fc8e9c85c494c1 
2021-07-05 00:28:18,993 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 00:28:18,994 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 00:28:19,017 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9100)
2021-07-05 00:28:22,002 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 00:28:22,006 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 00:28:22,007 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 5967
2021-07-05 00:31:06,636 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 13753) is connected !!!!
2021-07-05 00:31:11,269 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13753)
2021-07-05 00:31:20,388 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 13753), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:31:22,263 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 13770) is connected !!!!
2021-07-05 00:31:22,271 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13770)
2021-07-05 00:31:24,913 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 13770), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:35:32,025 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 13855) is connected !!!!
2021-07-05 00:35:32,031 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13855)
2021-07-05 00:35:32,035 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13855)
2021-07-05 00:35:39,218 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 13855), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:35:46,387 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 13862) is connected !!!!
2021-07-05 00:35:46,393 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13862)
2021-07-05 00:35:46,396 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13862)
2021-07-05 00:35:46,398 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13862)
2021-07-05 00:38:35,070 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 13862), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:41:32,256 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 13894) is connected !!!!
2021-07-05 00:42:57,381 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,549 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,551 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,553 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,555 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,556 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:04,558 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:43:31,377 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 13894)
2021-07-05 00:44:48,663 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 13894), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:46:41,147 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5009) is connected !!!!
2021-07-05 00:46:41,153 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5009)
2021-07-05 00:46:41,157 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5009)
2021-07-05 00:46:41,159 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5009)
2021-07-05 00:47:16,642 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5009), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:47:23,299 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5018) is connected !!!!
2021-07-05 00:47:23,309 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5018)
2021-07-05 00:47:23,318 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5018)
2021-07-05 00:49:05,066 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5018), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:49:10,211 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5037) is connected !!!!
2021-07-05 00:49:10,220 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5037)
2021-07-05 00:49:10,226 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5037)
2021-07-05 00:54:06,132 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5037), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:54:23,072 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5083) is connected !!!!
2021-07-05 00:54:30,605 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:30,610 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:30,611 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:30,613 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:30,615 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:30,617 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:54:36,101 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5083)
2021-07-05 00:56:56,897 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5083), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:57:41,946 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5101) is connected !!!!
2021-07-05 00:58:11,462 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5101), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:58:15,449 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5110) is connected !!!!
2021-07-05 00:58:15,455 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5110)
2021-07-05 00:58:15,457 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5110)
2021-07-05 00:58:18,162 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5110), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:58:19,113 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5114) is connected !!!!
2021-07-05 00:58:19,118 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5114)
2021-07-05 00:58:22,700 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5114), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:58:23,673 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5118) is connected !!!!
2021-07-05 00:58:23,678 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5118)
2021-07-05 00:58:25,819 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5118), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:58:26,797 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5122) is connected !!!!
2021-07-05 00:58:26,802 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5122)
2021-07-05 00:58:29,000 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5122), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 00:58:36,003 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5132) is connected !!!!
2021-07-05 00:58:36,008 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5132)
2021-07-05 00:58:36,010 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5132)
2021-07-05 00:58:36,012 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 5132)
2021-07-05 01:00:29,669 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5132), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 01:05:02,951 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1ea3e127440d2ab3ba215 mem_id=2015844693232
2021-07-05 01:05:02,952 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1ea3e127440d2ab3ba215 
2021-07-05 01:05:02,962 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 01:05:02,964 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 01:05:02,987 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9100)
2021-07-05 01:05:05,963 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 01:05:05,968 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 01:05:05,969 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 7193
2021-07-05 01:05:33,396 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5185) is connected !!!!
2021-07-05 01:05:47,491 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5185), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 01:07:48,612 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5202) is connected !!!!
2021-07-05 01:08:00,550 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5202), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 01:15:56,103 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5239) is connected !!!!
2021-07-05 01:20:08,836 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5239), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 01:20:22,272 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 5267) is connected !!!!
2021-07-05 01:20:30,590 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 5267), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-05 01:22:35,224 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1ee5b214e12981be0bdc4 mem_id=2430932940016
2021-07-05 01:22:35,225 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1ee5b214e12981be0bdc4 
2021-07-05 01:22:35,235 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 01:22:35,236 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 01:22:35,257 - INFO - RudpServer - [RudpServer.py:64]: RUDP Server on ('127.0.0.1', 9100)
2021-07-05 01:22:38,254 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 01:22:38,261 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-05 01:22:38,262 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 01:22:38,263 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-05 01:22:38,264 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 7818
2021-07-05 01:23:33,198 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1ee95dbc4fad6813e35e6 mem_id=1760176444512
2021-07-05 01:23:33,199 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1ee95dbc4fad6813e35e6 
2021-07-05 01:23:33,210 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 01:23:33,211 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 01:23:33,235 - INFO - RudpServer - [RudpServer.py:64]: RUDP Server on ('127.0.0.1', 9100)
2021-07-05 01:23:36,224 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 01:23:36,229 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-05 01:23:36,230 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 01:23:36,231 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-05 01:23:36,233 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 7849
2021-07-05 01:25:16,701 - INFO - RudpProtocol - [ConnMgr.py:111]: RUDP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 65278) is connected !!!!
2021-07-05 01:30:33,703 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1f039b5c6ab7a8c8607bb mem_id=2368103445792
2021-07-05 01:30:33,705 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f039b5c6ab7a8c8607bb 
2021-07-05 01:30:33,716 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 01:30:33,717 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 01:30:33,735 - INFO - RudpServer - [RudpServer.py:64]: RUDP Server on ('127.0.0.1', 9100)
2021-07-05 01:30:36,747 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 01:30:36,751 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 01:30:36,752 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 7929
2021-07-05 01:30:43,328 - INFO - RudpProtocol - [ConnMgr.py:111]: RUDP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 58899) is connected !!!!
2021-07-05 01:31:09,528 - INFO - RudpProtocol - [ConnMgr.py:111]: RUDP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 58901) is connected !!!!
2021-07-05 01:31:46,965 - INFO - ServerEntity.LoadCollector - [ServerEntity.py:25]: __init__ create entity LoadCollector with id 60e1f082bd8f53979b465f30 mem_id=2130695353632
2021-07-05 01:31:46,967 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1f082bd8f53979b465f30 
2021-07-05 01:31:46,976 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-05 01:31:46,978 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-05 01:31:46,997 - INFO - RudpServer - [RudpServer.py:64]: RUDP Server on ('127.0.0.1', 9100)
2021-07-05 01:31:49,984 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-05 01:31:49,989 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-05 01:31:49,990 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-05 01:31:49,991 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 7958
2021-07-05 01:32:04,227 - INFO - RudpProtocol - [ConnMgr.py:111]: RUDP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 63178) is connected !!!!
2021-07-05 01:32:07,080 - INFO - RudpProtocol - [ConnMgr.py:111]: RUDP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 63180) is connected !!!!
