2021-07-04 00:57:46,062 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:57:46,063 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:57:46,072 - INFO - TcpServer - [TcpServer.py:127]: Server on ('127.0.0.1', 9202)
2021-07-04 00:57:49,072 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:57:49,076 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:57:49,078 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:57:49,079 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:57:49,081 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9202)
2021-07-04 00:57:49,082 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9203)
2021-07-04 00:57:49,083 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1345
2021-07-04 00:58:02,085 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10915) is connected !!!!
2021-07-04 00:58:02,120 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10003) is connected !!!!
2021-07-04 00:58:02,122 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:217"]: self._try_connect_times=1, id(self._conn)=2808099953296
2021-07-04 00:58:04,897 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10924) is connected !!!!
2021-07-04 00:58:04,931 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:217"]: self._try_connect_times=1, id(self._conn)=2808099953296
2021-07-04 00:59:58,491 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:162"]: peer addr: ('127.0.0.1', 10924), close_reason='[WinError 64] The specified network name is no longer available'
