2021-07-04 00:19:39,577 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:19:39,578 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:19:39,586 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:19:42,601 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:19:42,605 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:19:42,607 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:19:42,608 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:19:42,609 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 681
2021-07-04 00:19:45,300 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 12204) is connected !!!!
2021-07-04 00:25:53,813 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:161"]: peer addr: ('127.0.0.1', 12204), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 00:26:26,111 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 12393) is connected !!!!
2021-07-04 00:26:32,624 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:161"]: peer addr: ('127.0.0.1', 12393), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 00:26:48,533 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 12404) is connected !!!!
2021-07-04 00:26:53,296 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:161"]: peer addr: ('127.0.0.1', 12404), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 00:27:28,299 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:27:28,300 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:27:28,308 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:27:31,187 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 12436) is connected !!!!
2021-07-04 00:27:31,314 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:27:31,318 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:27:31,320 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:27:31,322 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:27:31,323 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 972
2021-07-04 00:28:20,315 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:28:20,315 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:28:20,328 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:28:23,337 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:28:23,345 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:28:23,349 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:28:23,352 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:28:23,355 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 980
2021-07-04 00:28:36,519 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 12485) is connected !!!!
2021-07-04 00:41:13,177 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:41:13,179 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:41:13,186 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:41:16,188 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:41:16,192 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:41:16,194 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:41:16,195 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:41:16,196 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1000
2021-07-04 00:41:19,114 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:41:19,115 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:41:19,128 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:41:22,127 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:41:22,137 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:41:22,140 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:41:22,144 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:41:22,147 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1005
2021-07-04 00:41:27,943 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 9746) is connected !!!!
2021-07-04 00:42:03,716 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:42:03,717 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:42:03,734 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:42:06,736 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:42:06,745 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:42:06,749 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:42:06,752 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:42:06,755 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1029
2021-07-04 00:42:20,477 - INFO - ServiceFinder - [EtcdSupport.py:464]: recv watch expire, info--> lobby_0: ('127.0.0.1', 10001) - [1034]
2021-07-04 00:43:22,149 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 9819) is connected !!!!
2021-07-04 00:45:09,225 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:45:09,227 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:45:09,234 - INFO - TcpServer - [TcpServer.py:122]: Server on ('127.0.0.1', 9201)
2021-07-04 00:45:12,240 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:45:12,245 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:45:12,246 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:45:12,248 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1100
2021-07-04 00:45:32,423 - INFO - TcpServerProtocol - [TcpServer.py:84]: ('127.0.0.1', 9749) is connected !!!!
2021-07-04 00:50:35,190 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:50:35,192 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:50:35,199 - INFO - TcpServer - [TcpServer.py:124]: Server on ('127.0.0.1', 9201)
2021-07-04 00:50:37,706 - INFO - TcpServerProtocol - [TcpServer.py:86]: ('127.0.0.1', 9860) is connected !!!!
2021-07-04 00:50:38,204 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:50:38,209 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:50:38,210 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:50:38,211 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:50:38,212 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1167
2021-07-04 00:51:04,172 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:51:04,172 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:51:04,186 - INFO - TcpServer - [TcpServer.py:124]: Server on ('127.0.0.1', 9201)
2021-07-04 00:51:06,294 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:51:06,303 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:51:06,321 - INFO - TcpServer - [TcpServer.py:124]: Server on ('127.0.0.1', 9201)
2021-07-04 00:51:09,297 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:51:09,302 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:51:09,303 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:51:09,304 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1177
2021-07-04 00:51:21,558 - INFO - TcpServerProtocol - [TcpServer.py:86]: ('127.0.0.1', 9904) is connected !!!!
2021-07-04 00:56:06,028 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 00:56:06,030 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 00:56:06,037 - INFO - TcpServer - [TcpServer.py:127]: Server on ('127.0.0.1', 9201)
2021-07-04 00:56:08,029 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 9537) is connected !!!!
2021-07-04 00:56:09,053 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 00:56:09,058 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 00:56:09,059 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 00:56:09,060 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 00:56:09,061 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1279
2021-07-04 00:56:10,066 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10001) is connected !!!!
2021-07-04 00:56:10,068 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:217"]: self._try_connect_times=1, id(self._conn)=2165085807664
2021-07-04 00:57:34,891 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10873) is connected !!!!
2021-07-04 00:57:34,925 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:217"]: self._try_connect_times=1, id(self._conn)=2165085807664
2021-07-04 12:30:12,081 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 12:30:12,086 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 12:30:12,109 - INFO - TcpServer - [TcpServer.py:127]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 12:30:14,138 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 7982) is connected !!!!
2021-07-04 12:30:15,096 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 12:30:15,107 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 12:30:15,111 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 12:30:15,114 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 12:30:15,117 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1723
2021-07-04 12:30:15,187 - INFO - TcpServerProtocol - [TcpServer.py:89]: ('127.0.0.1', 10001) is connected !!!!
2021-07-04 12:30:15,191 - WARNING - ProxyLobbyRpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:218"]: self._try_connect_times=1, id(self._conn)=2663511756032
2021-07-04 14:51:02,329 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 14:51:02,331 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 14:51:02,352 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 14:51:05,350 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 14:51:05,355 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 14:51:05,356 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 14:51:05,358 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 14:51:05,359 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1735
2021-07-04 15:06:42,898 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 15:06:42,900 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 15:06:42,919 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 15:06:45,383 - INFO - TcpServerProtocol - [ConnMgr.py:52]: ('127.0.0.1', 14537) is connected !!!!
2021-07-04 15:06:45,903 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 15:06:45,908 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 15:06:45,909 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 15:06:45,910 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 15:06:45,912 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 1868
2021-07-04 15:06:46,420 - INFO - TcpServerProtocol - [ConnMgr.py:52]: ('127.0.0.1', 10001) is connected !!!!
2021-07-04 15:06:49,716 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:173"]: peer addr: ('127.0.0.1', 14537), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 21:13:43,012 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 21:13:43,014 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 21:13:43,032 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 21:13:46,037 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 21:13:46,042 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 21:13:46,043 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 21:13:46,044 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 21:13:46,045 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 2276
2021-07-04 21:14:00,201 - INFO - TcpProtocol - [ConnMgr.py:52]: ('127.0.0.1', 7622) is connected !!!!
2021-07-04 21:14:00,242 - INFO - TcpProtocol - [ConnMgr.py:52]: ('127.0.0.1', 10001) is connected !!!!
2021-07-04 22:18:31,413 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 22:18:31,415 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 22:18:31,422 - INFO - RudpServer - [RudpServer.py:64]: RUDP Server on ('127.0.0.1', 9201)
2021-07-04 22:18:34,434 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 22:18:34,451 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 22:18:34,452 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 22:18:34,453 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 22:18:34,454 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 2821
2021-07-04 22:25:27,197 - INFO - RudpProtocol - [ConnMgr.py:110]: ('127.0.0.1', 51891) is connected !!!!
2021-07-04 22:25:27,241 - INFO - RudpProtocol - [ConnMgr.py:130]: ('127.0.0.1', 10001) is connected !!!!
2021-07-04 22:29:49,353 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 22:29:49,355 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 22:29:49,363 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 22:29:52,372 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 22:29:52,376 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 22:29:52,378 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 22:29:52,379 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 22:29:52,380 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 3181
2021-07-04 22:39:22,912 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 22:39:22,915 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 22:39:22,923 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 22:39:25,926 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 22:39:25,930 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 22:39:25,932 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 22:39:25,933 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 22:39:25,934 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 3524
2021-07-04 22:39:30,562 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14789) is connected !!!!
2021-07-04 22:39:30,591 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 22:39:45,089 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:191"]: peer addr: ('127.0.0.1', 14789), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 22:43:42,852 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14840) is connected !!!!
2021-07-04 22:46:42,810 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 22:46:42,813 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 22:46:42,822 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 22:46:45,830 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 22:46:45,835 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 22:46:45,837 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 22:46:45,838 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 22:46:45,840 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 3692
2021-07-04 22:59:16,672 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 22:59:16,673 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 22:59:16,681 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 22:59:19,689 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 22:59:19,694 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 22:59:19,695 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 22:59:19,697 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 22:59:19,698 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 3710
2021-07-04 23:11:37,129 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:11:37,131 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:11:37,139 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:11:40,143 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:11:40,148 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:11:40,150 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:11:40,152 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:11:40,154 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4130
2021-07-04 23:14:29,650 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 13841) is connected !!!!
2021-07-04 23:16:14,839 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:16:14,840 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:16:14,849 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:16:17,852 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:16:17,857 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:16:17,859 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:16:17,860 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:16:17,861 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4256
2021-07-04 23:18:18,175 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3644) is connected !!!!
2021-07-04 23:18:21,576 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:18:35,830 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3644), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:18:37,246 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3652) is connected !!!!
2021-07-04 23:19:07,409 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:19:07,411 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:19:07,418 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:19:10,420 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:19:10,427 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:19:10,428 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:19:10,429 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:19:10,431 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4355
2021-07-04 23:19:11,011 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3667) is connected !!!!
2021-07-04 23:19:11,037 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:19:18,528 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3667), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:19:19,932 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3677) is connected !!!!
2021-07-04 23:19:32,691 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3677), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:19:34,043 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3682) is connected !!!!
2021-07-04 23:19:38,510 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3682), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:19:39,850 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3686) is connected !!!!
2021-07-04 23:22:09,037 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:22:09,038 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:22:09,046 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:22:12,053 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:22:12,058 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:22:12,060 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:22:12,061 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:22:12,063 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4389
2021-07-04 23:22:32,983 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3720) is connected !!!!
2021-07-04 23:22:33,017 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:22:36,219 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3720), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:22:37,563 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3725) is connected !!!!
2021-07-04 23:22:44,608 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3732) is connected !!!!
2021-07-04 23:22:51,132 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 3732), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:23:11,837 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:23:11,839 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:23:11,848 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:23:14,838 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:23:14,843 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:23:14,844 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:23:14,845 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:23:14,846 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4418
2021-07-04 23:23:15,466 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3746) is connected !!!!
2021-07-04 23:23:15,499 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:24:18,965 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 3766) is connected !!!!
2021-07-04 23:24:46,126 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 10001), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:24:48,224 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:24:48,835 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 1
2021-07-04 23:24:50,875 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:24:51,484 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 2
2021-07-04 23:24:53,537 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:24:54,146 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 3
2021-07-04 23:24:56,205 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:24:56,829 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 4
2021-07-04 23:24:58,874 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:24:59,480 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 5
2021-07-04 23:25:01,522 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:54"]: [WinError 1225] The remote computer refused the network connection
2021-07-04 23:25:02,134 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:57"]: try reconnect tcp: ('127.0.0.1', 10001) ... 6
2021-07-04 23:25:02,136 - ERROR - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:65"]: try 6 times , still can't connect tcp remote addr: ('127.0.0.1', 10001)
2021-07-04 23:25:15,274 - INFO - ServiceFinder - [EtcdSupport.py:464]: recv watch expire, info--> lobby_0: ('127.0.0.1', 10001) - [4487]
2021-07-04 23:35:13,485 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:35:13,486 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:35:13,498 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:35:16,512 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:35:16,521 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:35:16,525 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:35:16,528 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:35:16,531 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4734
2021-07-04 23:35:33,272 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:35:33,273 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:35:33,283 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:35:36,282 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:35:36,292 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:35:36,295 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:35:36,298 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:35:36,301 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4741
2021-07-04 23:35:42,133 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14049) is connected !!!!
2021-07-04 23:35:53,294 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:36:02,040 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14049), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:37:39,831 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14072) is connected !!!!
2021-07-04 23:37:44,480 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14072), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:39:04,882 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14082) is connected !!!!
2021-07-04 23:39:11,193 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14082), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:39:19,620 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14087) is connected !!!!
2021-07-04 23:39:57,468 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:39:57,469 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:39:57,481 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:40:00,489 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:40:00,497 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:40:00,501 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:40:00,504 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:40:00,507 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4894
2021-07-04 23:40:00,577 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14106) is connected !!!!
2021-07-04 23:40:00,612 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:40:13,134 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14106), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:40:20,741 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 14117) is connected !!!!
2021-07-04 23:47:34,867 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:47:34,869 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:47:34,877 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:47:37,874 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:47:37,879 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:47:37,881 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:47:37,882 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:47:37,884 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 4928
2021-07-04 23:47:53,613 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE ('127.0.0.1', 14175) is connected !!!!
2021-07-04 23:47:53,648 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE ('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:47:53,650 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:47:53,668 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14175)
2021-07-04 23:47:53,670 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14175)
2021-07-04 23:47:53,673 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:47:56,634 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:47:56,639 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14175)
2021-07-04 23:47:56,642 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14175)
2021-07-04 23:47:56,646 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:47:58,999 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14175), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:52:00,644 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE ('127.0.0.1', 14199) is connected !!!!
2021-07-04 23:52:00,676 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:00,692 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:00,694 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:00,700 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:03,679 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:03,685 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:03,689 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:03,698 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:06,690 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:06,694 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:06,699 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:06,706 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:09,688 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:09,693 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:09,695 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14199), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:52:09,699 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:52:09,705 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:55:48,047 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:55:48,049 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:55:48,058 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:55:51,065 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:55:51,069 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:55:51,071 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:55:51,073 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:55:51,074 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 5219
2021-07-04 23:55:56,195 - INFO - ServiceNode - [EtcdSupport.py:549]: we have create ServiceRegister
2021-07-04 23:55:56,195 - INFO - ServiceNode - [EtcdSupport.py:552]: we have create ServiceFinder
2021-07-04 23:55:56,207 - INFO - TcpServer - [TcpServer.py:100]: TCP Server on ('127.0.0.1', 9201)
2021-07-04 23:55:59,217 - INFO - ServiceFinder - [EtcdSupport.py:382]: _init_info, now_url: http://127.0.0.1:2379/v2/keys?recursive=true
2021-07-04 23:55:59,226 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_server: ('127.0.0.1', 10001)
2021-07-04 23:55:59,229 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> dispatcher_service: ('127.0.0.1', 9100)
2021-07-04 23:55:59,233 - INFO - ServiceFinder - [EtcdSupport.py:353]: add service node info--> lobby_gate: ('127.0.0.1', 9201)
2021-07-04 23:55:59,236 - INFO - ServiceFinder - [EtcdSupport.py:302]: init service info from etcd success, will going to watch, at etcd index -> 5226
2021-07-04 23:56:04,545 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 14247) is connected !!!!
2021-07-04 23:56:07,087 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 10001) is connected !!!!
2021-07-04 23:56:07,093 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:07,928 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:08,703 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:09,356 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:09,712 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:12,299 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:12,302 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:12,319 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:12,324 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:12,333 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:12,336 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:12,349 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:13,625 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:13,630 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:13,637 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:13,644 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:16,632 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:16,639 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:16,645 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:16,651 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:19,652 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:19,658 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:19,664 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:19,670 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:22,655 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:22,662 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:22,668 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 14247)
2021-07-04 23:56:22,674 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 10001)
2021-07-04 23:56:24,307 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 14247), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:57:14,495 - INFO - TcpProtocol - [ConnMgr.py:49]: TCP ROLE_TYPE_PASSIVE peer_addr=('127.0.0.1', 14259) is connected !!!!
