2021-06-29 00:12:37,455 - INFO - ServerEntity.ServerEntity - [ServerEntity.py:25]: __init__ create entity ServerEntity with id 60d9f4f5092cb9f0eac5a74e mem_id=1756110461824
2021-06-29 00:12:37,460 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d9f4f5092cb9f0eac5a74e 
2021-06-29 00:12:37,514 - DEBUG - __main__ - [TcpClient2.py:60]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-06-29 00:12:37,526 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60d9f4f5092cb9f0eac5a750 mem_id=1756111176368
2021-06-29 00:12:37,531 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d9f4f5092cb9f0eac5a750 
2021-06-29 00:18:35,020 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\TcpConn.py:163"]: peer addr: ('127.0.0.1', 9101), close_reason='connection is closed by error: [WinError 64] The specified network name is no longer available'
2021-06-29 00:20:01,258 - INFO - ServerEntity.ServerEntity - [ServerEntity.py:25]: __init__ create entity ServerEntity with id 60d9f6b1bee7b8e622fd1260 mem_id=2210467421056
2021-06-29 00:20:01,263 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d9f6b1bee7b8e622fd1260 
2021-06-29 00:20:01,321 - DEBUG - __main__ - [TcpClient2.py:60]: lobby server info: ('gate_2', '127.0.0.1', 9203)
2021-06-29 00:20:01,332 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60d9f6b1bee7b8e622fd1262 mem_id=2210468135600
2021-06-29 00:20:01,337 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60d9f6b1bee7b8e622fd1262 
